### ISSUE TITLE
batch size

### ISSUE THREAD

**Issue by JoungheeKim** [eenzeenee/T5_finetuning_for_summary#1]
안녕하세요! 실험과 관련되어 궁금한게 있어서 이슈를 남깁니다.
혹시 모델 학습에 사용한 GPU 스펙을 알 수 있을까요?

그리고 학습에 배치 사이즈 8 정도를 사용하신거 같은데 
배치 8에서도 만족할 만한 성능이 나오나요?

**Comment by eenzeenee** [comment]
안녕하세요! 확인이 늦어 이제라도 답변드립니다.

학습에 활용한 GPU는 NVIDIA-V100 1대 활용하였습니다.

학습 성능에 있어서는 rouge 스코어가 비교적 낮게 나타났으나 학습 결과를 확인하는 과정에서 진행한 프로젝트의 목적에 맞는 결과를 확인하여 해당 학습 배치 사이즈로 고정하였습니다. 다른 실험들도 동시에 진행하며 학습을 진행하여 메모리 에러가 나지 않도록 조정하는 단계에서 8이 최대치였는데 여유가 되신다면 추가적인 배치를 구성하여 실험해보시는것도 좋은 방법일 것 같습니다!
